"""
    Mechanism_Resolved_Deposition

A non-overlapping deposited-energy ledger for thin HTS layers, diagnostics, and detector response.
All arrays are indexed by `region_ids` and use MeV in the declared source-normalization basis.

Radiation-deposition channels are intentionally separated:

- `electronic_ionization_MeV`: ionization, excitation, and collisional electronic losses;
- `nuclear_recoil_MeV`: energy transferred to recoils and atomic motion in the scored region;
- `subcutoff_lattice_MeV`: transport energy terminated below the explicit particle cutoff and
  assigned to the local lattice/phonon sink;
- `delayed_decay_MeV`: energy deposited by time-labelled activation/decay sources;
- `other_radiation_MeV`: a named, provenance-bound residual radiation channel.

`joule_heating_MeV` is stored separately because it is generated by the electrical response, not
by radiation transport. It may be added only when constructing a coupled thermal source.
"""
struct Mechanism_Resolved_Deposition
    region_ids::Vector{Int64}
    electronic_ionization_MeV::Vector{Float64}
    nuclear_recoil_MeV::Vector{Float64}
    subcutoff_lattice_MeV::Vector{Float64}
    delayed_decay_MeV::Vector{Float64}
    other_radiation_MeV::Vector{Float64}
    joule_heating_MeV::Vector{Float64}
    normalization::Source_Normalization
    provenance::Dict{String,String}

    function Mechanism_Resolved_Deposition(
        region_ids::AbstractVector{<:Integer};
        electronic_ionization_MeV::AbstractVector{<:Real},
        nuclear_recoil_MeV::AbstractVector{<:Real},
        subcutoff_lattice_MeV::AbstractVector{<:Real},
        delayed_decay_MeV::AbstractVector{<:Real},
        other_radiation_MeV::AbstractVector{<:Real},
        joule_heating_MeV::AbstractVector{<:Real},
        normalization::Source_Normalization,
        provenance::AbstractDict=Dict{String,String}(),
        negative_tolerance::Real=1.0e-14,
    )
        ids = Int64.(region_ids)
        isempty(ids) && error("At least one deposition region is required.")
        length(unique(ids)) == length(ids) || error("Deposition region identifiers must be unique.")
        tolerance = Float64(negative_tolerance)
        isfinite(tolerance) && tolerance ≥ 0.0 || error("Negative tolerance must be finite and nonnegative.")

        channels = [
            Float64.(electronic_ionization_MeV),
            Float64.(nuclear_recoil_MeV),
            Float64.(subcutoff_lattice_MeV),
            Float64.(delayed_decay_MeV),
            Float64.(other_radiation_MeV),
            Float64.(joule_heating_MeV),
        ]
        all(length(channel) == length(ids) for channel in channels) || error(
            "Every deposition channel must have one value per region.",
        )
        for channel in channels
            any(value -> !isfinite(value) || value < -tolerance,channel) && error(
                "Deposited-energy channels must be finite and nonnegative.",
            )
            channel[abs.(channel) .≤ tolerance] .= 0.0
        end
        provenance_string = Dict{String,String}(string(key)=>string(value) for (key,value) in provenance)
        return new(ids,channels...,normalization,provenance_string)
    end
end

function get_radiation_deposition(this::Mechanism_Resolved_Deposition;physical::Bool=false)
    values = this.electronic_ionization_MeV .+
             this.nuclear_recoil_MeV .+
             this.subcutoff_lattice_MeV .+
             this.delayed_decay_MeV .+
             this.other_radiation_MeV
    return physical ? apply_normalization(values,this.normalization) : values
end

function get_total_heat_source(this::Mechanism_Resolved_Deposition;physical::Bool=false)
    values = get_radiation_deposition(this) .+ this.joule_heating_MeV
    return physical ? apply_normalization(values,this.normalization) : values
end

function assert_deposition_closure(
    this::Mechanism_Resolved_Deposition,
    reference_radiation_deposition_MeV::AbstractVector{<:Real};
    rtol::Real=1.0e-10,
    atol::Real=1.0e-12,
)
    reference = Float64.(reference_radiation_deposition_MeV)
    calculated = get_radiation_deposition(this)
    length(reference) == length(calculated) || error("Reference deposition must match the region count.")
    all(isapprox(calculated[index],reference[index];rtol=rtol,atol=atol) for index in eachindex(calculated)) || error(
        "Mechanism-resolved radiation deposition does not close to the reference.",
    )
    return true
end
