# This is the explicit temporary loader for HTS completion modules that will move together into
# RadiantHTS.jl. Keeping this list in one file avoids scattering nested includes through generic
# Radiant transport kernels. Include order is dependency order.

include(joinpath(@__DIR__,"CSV_Utilities.jl"))
include(joinpath(@__DIR__,"Gd_Evaluated_Cascade_Adapter.jl"))
include(joinpath(@__DIR__,"Response_Table_Completion.jl"))
include(joinpath(@__DIR__,"Material_Data_Bindings.jl"))
include(joinpath(@__DIR__,"Curvature_Convergence_Study.jl"))
include(joinpath(@__DIR__,"Physical_Reference_Artifact.jl"))
include(joinpath(@__DIR__,"Layer_Heating_Ledger.jl"))
include(joinpath(@__DIR__,"Gd_Self_Shielding_Analytic.jl"))
include(joinpath(@__DIR__,"Response_Preserving_Group_Condensation.jl"))
include(joinpath(@__DIR__,"Activation_Delayed_Source.jl"))

export Evaluated_Gd_Cascade_Dataset,read_evaluated_gd_cascade_csv
export evaluated_gd_dataset_is_production_ready,gd_dataset_receipt
export SUBKEV_PARTITION_CHANNELS

export Tabulated_Material_Property,material_property_standard_uncertainty
export register_material_property!,cryogenic_property_from_atomistic_table
export material_record_from_atomistic_table,subkev_kernel_from_atomistic_table
export hts_material_response_source_map

export Layer_Heating_Contribution,Layer_Heating_Ledger,heating_ownership_key
export add_heating_contribution!,get_heating_contribution,production_heating_total
export heating_comparison_set,validate_population_energy_closure
export validate_heating_ledger,heating_ledger_receipt

export Gd_Groupwise_Capture_Component,Gd_Self_Shielding_Layer
export Gd_Self_Shielding_Cell_Result,Gd_Groupwise_Self_Shielding_Result
export macroscopic_capture_cm_inv,solve_gd_groupwise_self_shielding
export gd_groupwise_self_shielding_factor,capture_rate_field_from_gd_self_shielding
export gd_self_shielding_receipt

export Energy_Group_Condensation_Map,fine_group_count,coarse_group_count
export condense_group_integrals,response_condensation_weight_matrix
export Response_Condensation_Receipt,condense_response_coefficients
export condense_response_covariance,group_condensation_map_hash
export Transfer_Matrix_Condensation_Receipt,condense_transfer_matrix
export response_condensation_receipt,transfer_matrix_condensation_receipt

export Delayed_Emission_Bin,Delayed_Decay_Scheme,Delayed_Activity_Field
export Delayed_NonEM_Handoff,Activation_Delayed_Source_Bundle
export build_activation_delayed_source_bundle,activation_delayed_bundle_is_production_ready
export activation_delayed_source_receipt,synthetic_activation_decay_fixture
